name: Cypress Tests
on:
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ralphie
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      AUTH0_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.NEXT_PUBLIC_AUTH0_CLIENT_SECRET }}
      AUTH0_COOKIE_SECRET: ${{ secrets.NEXT_PUBLIC_AUTH0_COOKIE_SECRET }}
      AUTH0_DOMAIN: ${{ secrets.NEXT_PUBLIC_AUTH0_DOMAIN }}
      DATABASE_URL: postgres://postgres:ralphie@postgres:5432/postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup code
        run: yarn

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/automated/**/*
          build: yarn build
          start: yarn start
