name: Cypress Tests
on:
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Setup code
        uses: actions/checkout@v2
        run: |
          yarn
          yarn dev

      - name: Cypress run
        env:
          # CYPRESS_CE_USER: ${{ secrets.CYPRESS_CE_USER }}
          # CYPRESS_CE_PASS: ${{ secrets.CYPRESS_CE_PASS }}
          CYPRESS_BASE_URL: http://localhost:3000/
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/automated/**/*
